// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSBmok8nWql_K7uBaklLMyJ6iRpUXKfo',
    appId: '1:984439275752:web:94250fe0d538eec47e895d',
    messagingSenderId: '984439275752',
    projectId: 'socialapp-52c36',
    authDomain: 'socialapp-52c36.firebaseapp.com',
    storageBucket: 'socialapp-52c36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU9HMgFZUOhnk0ocEOLYUOtFjrA7jWlnE',
    appId: '1:984439275752:android:3eec4807911a038d7e895d',
    messagingSenderId: '984439275752',
    projectId: 'socialapp-52c36',
    storageBucket: 'socialapp-52c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP_U09tVvfUjarsGWcoLMB_sb3vPERtxI',
    appId: '1:984439275752:ios:23ba5ac63dc7d2347e895d',
    messagingSenderId: '984439275752',
    projectId: 'socialapp-52c36',
    storageBucket: 'socialapp-52c36.appspot.com',
    iosBundleId: 'com.example.socialNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP_U09tVvfUjarsGWcoLMB_sb3vPERtxI',
    appId: '1:984439275752:ios:23ba5ac63dc7d2347e895d',
    messagingSenderId: '984439275752',
    projectId: 'socialapp-52c36',
    storageBucket: 'socialapp-52c36.appspot.com',
    iosBundleId: 'com.example.socialNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdSBmok8nWql_K7uBaklLMyJ6iRpUXKfo',
    appId: '1:984439275752:web:e80d80c59673b6307e895d',
    messagingSenderId: '984439275752',
    projectId: 'socialapp-52c36',
    authDomain: 'socialapp-52c36.firebaseapp.com',
    storageBucket: 'socialapp-52c36.appspot.com',
  );
}
